version: '3'
services:
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    container_name: db
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=maxMilhas
    restart: always
    networks:
      - networkName

  backend:
    build: ./
    container_name: DB_MAX_MILHAS
    restart: always
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_NAME=maxMilhas
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - networkName

networks:
  networkName:
    driver: bridge
